export const STAGE_PROBABILITY = {
  RFQ: 10,
  VISIT_MEETING: 20,
  PREVIEW: 30,
  TECHNICAL_PROPOSAL: 40,
  COMMERCIAL_PROPOSAL: 50,
  REVIEW_FEEDBACK: 60,
  MOVED_TO_PURCHASE: 75,
  NEGOTIATION: 90,
  CLOSED_WON: 100,
  CLOSED_LOST: 0,
  CLOSED_LOST_TO_COMPETITION: 0,
  REGRETTED: 0,
};

export const getStageProbability = (stage) =>
  STAGE_PROBABILITY[stage] ?? 0;